# GitHub Actions workflow configuration file
# This workflow runs automated tests on push and pull request events
name: GitHub Actions Setup

# Trigger the workflow on push and pull request events
on: [push, pull_request]  # Runs on every push or PR

# Define jobs to be executed
jobs:
  # Test job that runs the automated tests
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Print confirmation message to verify workflow is working
      - name: Confirm GitHub Actions is Working
        run: echo "GitHub Actions is successfully set up!"
